accounts/urls.py
from django.urls import path,reverse_lazy
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(),name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path('ajax/load_notification/',views.get_new_notification, name='load_notification'),
    path('notifications/',views.NotificationView.as_view(), name='notifications'),
    path('notifications/<pk>',views.notifications_redirectView, name='notifications_redirect'),
    path('notifications/<pk>/remove/',views.notifications_remove, name='notifications_remove'),
    path('notifications/<pk>/mark_as_read',views.notifications_markread, name='notifications_markread'),

    path("profile/",
        views.myProfileView,
        name="myprofile"),
    path("change_password",
        views.UserPasswordChang.as_view(),
        name="changepassword"),
    path("profile/<username>/edit",
        views.ProfileUpdateView.as_view(),
        name="edit"),
    path("ajax/made_consultant/<username>", views.made_consultant, name="made-consultant"),

    path("", views.UserListView.as_view(), name="list"),

    path("profile/<username>",
        views.ProfileUpdateView.as_view(),
        name="profile"),


    path("password-reset/",
        auth_views.PasswordResetView.as_view(template_name='accounts/password_reset_form.html',
                                            email_template_name="accounts/password_reset_email.html",
                                            success_url= reverse_lazy("login")),
        name="password-reset"),
    path("reset/<uidb64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',

                                                    success_url= reverse_lazy("home")    ),
        name="password_reset_confirm"),
    path("new_user/", views.NewUser.as_view(), name="new"),


]

clients/urls.py
from django.urls import path
from . import views
from accounts.views import NewUser as new_user

app_name = 'clients'

urlpatterns = [
    path("", views.ClientsList.as_view(),name='list'),
    path("new/", views.ClientsCreate.as_view(), name="new"),
    path("new_user/", new_user.as_view(), name="new_user"),

    #path("new/", views.clientsCreate, name="new"),

    #path("<slug>/", views.ClientsDetail.as_view(), name="detail"),
    path("<slug>/", views.ClientsUpdate.as_view(), name="detail"),

    path("<slug>/delete", views.ClientsDelete.as_view(), name="delete"),
    path("<slug>/edit", views.ClientsUpdate.as_view(), name="edit"),




]

ntonSulotions/urls.py
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf.urls import handler400, handler403, handler404, handler500
from django.conf import settings
from django.contrib import admin
from . import views

# urlpatterns = [path('?admin/', admin.site.urls), ]
  #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

# urlpatterns = i18n_patterns(
#     path("csv", views.csv_view, name="csv"),
#     path('i18n/', include('django.conf.urls.i18n')),
#     path('', views.HomePage.as_view(), name="home"),
#     path("admin/", admin.site.urls),
#     path("accounts/", include("accounts.urls", namespace="accounts")),
#     path("accounts/", include("django.contrib.auth.urls")),
#     path("ticket/", include("solutions.urls", namespace="solutions")),
#     path('client/', include('clients.urls',namespace='clients')),
#     path('set_language/<user_language>', views.set_language_from_url, name="set_language_from_url")
# )
urlpatterns = (
    path("csv", views.csv_view, name="csv"),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', views.HomePage.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("ticket/", include("solutions.urls", namespace="solutions")),
    path('client/', include('clients.urls',namespace='clients')),
    path('set_language/<user_language>', views.set_language_from_url, name="set_language_from_url")
)

handler400 = 'ntonSulotions.views.handler400'
handler403 = 'ntonSulotions.views.handler403'
handler404 = 'ntonSulotions.views.handler404'
handler500 = 'ntonSulotions.views.handler500'

solutions/urls.py
from django.urls import path, include, re_path
from . import views

app_name='solutions'


urlpatterns = [


    path('<int:pk>/', views.QuestionSingle.as_view(), name='questiondetail'),
    path('<int:pk>/edit',views.QuestionEdit.as_view(),name='questionedit'),
    path('nouvou/',views.QuestionCreate.as_view(),name='questioncreate'),
    path('<int:pk>/addanswere/',views.add_reponce_to_question,name='questionereponder'),
    path('<int:pk>/resolved/',views.questioneResolved,name='questioneResolved'),
    path('<int:pk>/charged/',views.questioneCharged,name='questioneCharged'),

    #path('page/<int:page>/',views.QuestionList.as_view(),name='questionlistpages'),
    path('',views.QuestionList.as_view(),name='questionlist'),
    path('ajax/load-categories/', views.load_categories, name='ajax_load_categorie'),
    path('ajax/load-chart/', views.load_chart, name='ajax_load_chart'),






]

solutions/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _

from django.db.models import Max
import os
import datetime
import uuid

from django.conf import settings
User = settings.AUTH_USER_MODEL



# Create your models here.
class Categorie(models.Model):
    """Django data model Categorie"""
    name = models.CharField(blank=True, max_length=100)
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categorys'
    def __str__(self):
        return str(self.name)

class SousCategorie(models.Model):
    """Django data model SousCategorie"""
    name = models.CharField(blank=True, max_length=100)
    categorie = models.ForeignKey('Categorie', on_delete=models.CASCADE, related_name='SousCategories',)
    class Meta:
        verbose_name = 'Sub-category'
        verbose_name_plural = 'Sub-categorys'
    def __str__(self):
        return str(self.categorie.name + '/'+self.name)

class Question(models.Model):

###           Priorite           ###
    Priorite=(
        ('F', _('Low')),
        ('M', _('Medium')),
        ('H', _('Height')),
        ('U', _('Urgent')),
        ('B',_('Blocking'))
        )
###           Status             ###
    Status= (
        ('EA', _('Waiting')),
        ('RS', _('Resolved')),
        ('OV', _('Open')),
        ('FR', _('Closed')),
        ('RF', _('Refused')),
        ('AN', _('Canceled')),
        ('DS', _('Deactiveted')),
        )

    def content_file_name(instance, filename):
        filename = "%s__%s" % (uuid.uuid4().hex[:6].upper(),filename)
        return os.path.join('images', str(instance.user.id), filename)
    def ref():
        this_year = datetime.date.today().year
        no = Question.objects.filter(created_at__year=this_year).aggregate(Max('ref')).get('ref__max')
        if no == None:
            return 1
        else:
            return  no + 1
    user = models.ForeignKey(User,null=True, related_name="tickets",on_delete=models.SET_NULL)
    ref = models.PositiveIntegerField(default=ref, verbose_name='Reference')
    # ref = models.CharField(default=ref, unique=True, editable=False,  max_length=100)
    created_at = models.DateTimeField(auto_now_add=True,editable=False)
    objet = models.CharField(max_length=200)
    image = models.ImageField(blank=True,null=True, upload_to=content_file_name)
    priorite=models.CharField(max_length=1,choices=Priorite,default='F',)
    status = models.CharField(max_length=2,choices=Status,default='OV',)
    priorite_intern = models.CharField(max_length=2, verbose_name=_('Internal priority'), choices=Priorite,default='F',blank=True,null=True)

    categorie = models.ForeignKey(Categorie,verbose_name=_('Category'), on_delete=models.CASCADE, related_name='quesions',)
    souscategorie = models.ForeignKey(SousCategorie, verbose_name=_('Sub-category'), on_delete=models.CASCADE, related_name='quesions',)

    description = models.TextField(blank=True,verbose_name=_('comment'))
    viwed_at = models.DateTimeField(blank=True,null=True)
    time_to_view = models.DurationField(blank=True,null=True,verbose_name=_('time to view'))
    charged_by = models.ForeignKey(User,null=True, related_name="charged_tickets",on_delete=models.SET_NULL)

    first_react_at = models.DateTimeField(blank=True,null=True)
    time_to_react = models.DurationField(blank=True,null=True,verbose_name=_('time to react'))
    resolved_at = models.DateTimeField(blank=True,null=True)
    time_to_resolv = models.DurationField(blank=True,null=True,verbose_name=_('Time to resolve'))
    last_action = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):

        if self.status != 'RS':
            self.resolved_at = None
            self.time_to_resolv = datetime.timedelta(0)
        if self.viwed_at:
            self.time_to_view = self.viwed_at - self.created_at
        if self.first_react_at:
            self.time_to_react = self.first_react_at - self.created_at
        if self.resolved_at  != None:
            self.time_to_resolv = self.resolved_at - self.created_at




        super().save(*args, **kwargs)

    def get_ref(self):
        return '{}-{}'.format(self.created_at.year,self.ref)
    def date_to_string(self,date, string, *args):
        if date:
            days = date.days
            sec = date.seconds
            if days == 1:
                return '%02d %s %02d H %02d M' % (days, _('Day'),int((sec/3600)%3600), int((sec/60)%60))
            if days > 1:
                return '%02d %s %02d H %02d M' % (days, _('Days'),int((sec/3600)%3600), int((sec/60)%60))
            return '%02d H %02d M' % (int((sec/3600)%3600), int((sec/60)%60))
        return string
    def get_time_to_resolv(self):
        string = _("Not resolved yet")
        return self.date_to_string(self.time_to_resolv, string)
    def get_time_to_view(self):
        string = _("Not viewed yet")
        return self.date_to_string(self.time_to_view, string)
    def get_time_to_react(self):
        string = _("Not reacted yet")
        return self.date_to_string(self.time_to_react, string)
    def get_resolved_at(self):
        if self.resolved_at: return self.resolved_at.strftime('%m/%d/%Y %H:%m')
        else : return  _("Not resolved yet")

    Color = {}
    Color['F'] = 'secondary'
    Color['M'] = 'primary'
    Color['H'] = 'success'
    Color['U'] = 'danger'

    def get_color(self):
        return self.Color.get(self.priorite)

    def get_categorie(self):
        return self.categorie.name + '/' + self.souscategorie.name

    def get_absolute_url(self):
            return reverse_lazy("solutions:questiondetail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.objet

    class Meta:
        ordering = ["-created_at"]
        verbose_name = _('Ticket')
        verbose_name_plural = _('Tickets')

class Reponce(models.Model):
    Status= (
        ('EA', _('Waiting')),
        ('RS', _('Resolved')),
        ('FR', _('Closed')),
        ('RF', _('Refused')),
        )
    user = models.ForeignKey(User,null=True, related_name="reponces",on_delete=models.SET_NULL)
    created_at = models.DateTimeField(auto_now_add=True,editable=False,)
    description = models.TextField(null=True, blank=True,)
    question = models.ForeignKey(Question,null=True, related_name="reponces",on_delete=models.SET_NULL)
    status = models.CharField(max_length=2,choices=Status,default='EA',)
    send_mail = models.BooleanField(default=False)
    def __str__(self):
        return self.description
    class Meta:
        ordering = ["-created_at"]

solutions/forms.py
from django import forms
from django.db import IntegrityError
from django.contrib import messages
from django.contrib.auth import get_user_model
User = get_user_model()
from django.utils.translation import gettext_lazy as _
from .models import Reponce, Question, Categorie, SousCategorie

class ReponceForm(forms.ModelForm):

    class Meta:
        model = Reponce
        fields = ( 'description','status','send_mail')

class QuestionForm(forms.ModelForm):

    class Meta:
        fields = ("categorie","souscategorie","objet","priorite","image", "description",'priorite_intern')
        model = Question

    def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            # print('in form')
            self.fields['souscategorie'].queryset = SousCategorie.objects.none()
            if 'categorie' in self.data:
                try:
                    categorie = int(self.data.get('categorie'))
                    self.fields['souscategorie'].queryset = SousCategorie.objects.filter(categorie=categorie).order_by('name')
                except (ValueError, TypeError):
                    pass
            elif self.instance.pk:
                categorie = int(self.data.get('categorie'))
                self.fields['souscategorie'].queryset = SousCategorie.objects.filter(categorie=categorie).order_by('name')
    def clean(self):
            self.image = self.cleaned_data['image']
            return

solutions/templates/solutions/action.html
{% load i18n %}
{% load static %}
{% if reponce.user.is_staff %}
  <li style="width:100%">
        <div class="msj macro">
          <div class="avatar align-bottom"><img class="rounded-circle " style="width:100%;" src='{% static "img/avatar-admin.png" %}' /></div>
              <div class="actiontext text-l">
                  <p>{{ reponce.description|safe|linebreaks }} </p>
                  <p><small>{% trans "by" %} {{ reponce.user }} {{ reponce.created_at|date:"d/M/Y H:m" }}</small></p>
              </div>
          </div>
  </li>
{% else %}
  <li style="width:100%;">
      <div class="msj-rta macro">
          <div class="actiontext text-r">
              <p>{{ reponce.description|safe|linebreaks }}</p>
              <p><small>{% trans "by" %}  {{ reponce.user }} {{ reponce.created_at|date:"d/M/Y H:m" }}</small></p>
          </div>
      <div class="avatar align-bottom" style="padding:0px 0px 0px 10px !important"><img class="rounded-circle" style="width:100%;" src='{% static "img/avatar.png" %}' /></div>
  </li>
{% endif %}

solutions/templates/solutions/categorie_dropdown_list_options.html
{% for categorie in souscategorie %}
<option value="{{ categorie.pk }}">{{ categorie.name }}</option>
{% endfor %}

solutions/templates/solutions/question_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% load i18n %}

{% block body_block %}


<div class="row row-col-1">
  <div class="col-12">
    <ul class="nav nav-tabs nav justify-content-center" id="list-tab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home">Ticket</a>
      </li><li class="nav-item">
        <a class="nav-link" id="list-profile-list" data-toggle="list" href="#list-profile" role="tab" aria-controls="profile">{% trans "Ticket's traitment" %}</a>
      </li><li class="nav-item">
        <a class="nav-link" id="list-statistics-list" data-toggle="list" href="#list-statistics" role="tab" aria-controls="profile">{% trans "historic" %}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="list-messages-list" data-toggle="list" href="#list-messages" role="tab" aria-controls="messages"></a>
      </li>
      <li class="nav-item px-1"><a class="btn btn-nton" href="{% url 'solutions:questionedit' pk=question.pk %}">{% trans "Edit" %}</a>
      </li>
      {% if  question.status != "RS"%}
      <li class="nav-item px-1">
        <form class="" action="{% url 'solutions:questioneResolved' pk=question.pk %}" method="post">
          {% csrf_token %}
          <button class="btn btn-nton" type="submit" name="button">{% trans "Resolved" %}</button>
        </form>
      </li>
      {% endif %}
      {% if not question.charged_by == request.user and request.user.is_staff %}
      <li class="nav-item px-1">
        {% comment %} <form class="" action="{% url 'solutions:questioneCharged' pk=question.pk %}" method="post"> {% endcomment %}
          {% csrf_token %}
        <a id="charged" class="btn btn-nton" href="javascript:void(0)" >{% trans "Take in charge" %} </a>
        {% comment %} </form> {% endcomment %}
      </li>
      <script type="text/javascript">
          $("#charged").click(function () {
          $.ajax({
            url: "http://{{request.META.HTTP_HOST}}{% url 'solutions:questioneCharged' pk=question.pk %}",
            success: function (json) {
                $("#charged").remove();
                $('#actionul').prepend(json.html_content);
                $('#noAction').remove();
                $('#last_action').html(json.last_action);
                $('#time_toreact').html(json.time_toreact);
                $('#time_toresolv').html(json.time_toresolv);
                $('#resolved_at').html(json.resolved_at);
                $('#status_display').html(json.status_display);

          }});
          });
          </script>


          {% endif %}
    </ul>
    </div>
    <div class="tab-content w-100" id="nav-tabContent">
      <div class="tab-pane fade show active w-100" id="list-home" role="tabpanel" aria-labelledby="list-home-list">
        <table class="table table-borderless  mx-xs-2 ">
          <tbody class="row row-col-1  no-gutters">
            <tr class="col-12 bg-light text-center align-self-center">
              <th class="">Id</th>
              <td>{{question.get_ref}}</td>

            </tr>
            <div class="col-12 row">
              <tr class="col-md-6 col-sm-12 row no-gutters">
                <th class="col-4 bg-light">{% trans "Open date" %}</th>
                <td class="col bg-white" >{{question.created_at|date:"Y-m-d H:m"}}</td>
              </tr>
              <tr class="col-md-6 col-sm-12 row no-gutters">
                <th class="col-4 bg-light">{% trans "By" %}</th>
                <td class="col bg-white">{{question.user}}</td>
              </tr>
            </div>

            <tr class="col-12 col-sm-12 col-sm-12 row no-gutters">
              <th class="col-2 bg-light">{% trans "Last edit" %}</th>
              <td id="last_action" class="col bg-white">{{question.last_action|date:"Y-m-d H:m"}}</td>
            </tr>
            <tr class="col-md-6  col-sm-12 row no-gutters">
              <th class="col-4 bg-light">{% trans "Time to react" %}</th>
              <td id="time_toreact" class="col-8 bg-white">{{question.get_time_to_react}}</td>
            </tr>
            <tr class="col-md-6 col-sm-12 row no-gutters">
              <th class="col-4  bg-light">{% trans "Time to resolve" %}</th>
              <td id="time_toresolv" class="col-8 bg-white">{{question.get_time_to_resolv}}</td>
            </tr>
            <tr class="col-12 col-sm-12 row no-gutters">
              <th class="col-2 bg-light">{% trans "Resolved at" %}</th>
              <td id="resolved_at" class="col  bg-white ">{{question.resolved_at|date:"Y-m-d H:m"}}</td>
            </tr>
            <tr class="col-md-6 col-sm-12 row no-gutters">
              <th class="col-4 bg-light">{% trans "Status" %}</th>
              <td id='status_display' class="col bg-white">{{question.get_status_display}}</td>
            </tr>
            <tr class="col-md-6 col-sm-12 row no-gutters">
              <th class="col-4 bg-light">{% trans "Priority" %}</th>
              <td class="col bg-white">{{question.get_priorite_display}}</td>
            </tr>
            <tr class="col-md-12 col-sm-12 row no-gutters">
              <th class="col-2 bg-light">{% trans "Categorie" %}</th>
              <td class="col bg-white">{{question.categorie.name}}/{{question.souscategorie.name}}</td>
            </tr>
            <tr class="col-md-12 col-sm-12 row no-gutters">
              <th class="col-2 bg-light">{% trans "Title" %}</th>
              <td class="col bg-white">{{question.objet }}</td>
            </tr>
            <tr class="col-md-12 col-sm-12 row no-gutters">
              <th class="col-2 bg-light">{% trans "Description" %}</th>
              <td class="col bg-white">{{question.description|safe}}</td>
            </tr>
            <tr class="col-md-12 col-sm-12 row no-gutters">
              <td class="col ">
                {% if question.image %}
                <a href="{{question.image.url}}">
                <img src="{{question.image.url}}" height="50%" width="50%" alt="">
                </a>
                {% endif %}
              </td>
            </tr>



          </tbody>
        </table>
      </div>
      <div class="tab-pane fade w-100" id="list-profile" role="tabpanel" aria-labelledby="list-profile-list">
        <h4>Action</h4>
        <form id='action_form' method="post" action="{% url 'solutions:questionereponder' pk=question.pk %}">
          {% csrf_token %}
          <div class="row row-col-1">
            <div class="col-sm-12">
              <div class="wmd-panel">
                <link rel="stylesheet" href="{% static "css/medium-editor.css" %}">
                <link rel="stylesheet" href="{% static "css/themes/default.css" %}" id="medium-editor-theme">

                <div class="form-group row bmd-form-group border">
                  <label class="col-md-3 col-form-label sr-only bmd-label-static" for="id_description">Description</label>
                  <div class="form-control-full col-md-12">
                    <textarea name="description" class="editable medium-editor-textarea" data-placeholder="Description" placeholder="Description" title="" id="id_description">
                    </textarea>
                  </div>
                </div>
                {% bootstrap_field form.status  placeholder='' show_label=False layout='horizontal'  %}
                  <div class="col-md-9">
                    {% if not request.user.is_staff %} <!-- {% endif %}
                    <div class="form-group" >
                      <div class="form-check">
                        <label class="form-check-label">
                            <input type="checkbox" name="send_mail"
                            class="form-check-input " id="id_send_mail" >
                            {% trans "Send mail" %}
                            <span class="form-check-sign">
                                <span class="check"></span>
                            </span>
                        </label>
                      </div>
                    </div>
                    {% if not request.user.is_staff %} --> {% endif %}
                    <button type="submit" class="save btn btn-info pull-right">{% trans "Save" %}.</button>
                  </div>
              </div>
            </div>

          </div>
        </form>
        <script type="text/javascript">
          $(document).on('submit', '#action_form', function(e){
            e.preventDefault();
            send_mail = 'False';
            {% if request.user.is_staff %}
            if($('#id_send_mail'). is(":checked")){
              send_mail = 'True';
              }
            {% endif %}
            $.ajax({
              type:'POST',
              url : '{% url "solutions:questionereponder" pk=question.pk %}',
              data : {
                description : $('#id_description').val().trim(),
                status : $("#id_status").children("option:selected").val(),
                send_mail : send_mail,
                csrfmiddlewaretoken : $('input[name=csrfmiddlewaretoken]').val(),
                action : 'post'
              },
              success:function(json){
                document.getElementById("action_form").reset();
                console.log(json);
                $('#actionul').prepend(json.html_content);
                $('#noAction').remove();
                $('#last_action').html(json.last_action);
                $('#time_toreact').html(json.time_toreact);
                $('#time_toresolv').html(json.time_toresolv);
                $('#resolved_at').html(json.resolved_at);
                $('#status_display').html(json.status_display);
                // $('#actionul').html(json.html_content);
                // $('#actionul').html(json.html_content);
                //
              },
            });
          });
        </script>
        <div class="frame">
          <ul class="actionul" id='actionul'>
            {% for reponce in question.reponces.all %}
              {% if reponce.user.is_staff %}
                <li style="width:100%">
                      <div class="msj macro">
                        <div class="avatar align-bottom"><img class="rounded-circle " style="width:100%;" src='{% static "img/avatar-admin.png" %}' /></div>
                            <div class="actiontext text-l">
                                <p>{{ reponce.description|safe|linebreaks }} </p>
                                <p><small>{% trans "by" %} {{ reponce.user }} {{ reponce.created_at|date:"d/M/Y H:m" }}</small></p>
                            </div>
                        </div>
                </li>
              {% else %}
                <li style="width:100%;">
                    <div class="msj-rta macro">
                        <div class="actiontext text-r">
                            <p>{{ reponce.description|safe|linebreaks }}</p>
                            <p><small>{% trans "by" %}  {{ reponce.user }} {{ reponce.created_at|date:"d/M/Y H:m" }}</small></p>
                        </div>
                    <div class="avatar align-bottom" style="padding:0px 0px 0px 10px !important"><img class="rounded-circle" style="width:100%;" src='{% static "img/avatar.png" %}' /></div>
                </li>
              {% endif %}
            {% empty %}
            <p id="noAction">{% trans "No action" %}.</p>
            {% endfor %}
          </ul>
        </div>
      </div>
      <div class="tab-pane fade w-100" id="list-statistics" role="tabpanel" aria-labelledby="list-statistics-list">
        <h3>{% trans "historic" %}</h3>
        <h4 class="text-center bg-dark py-2 text-white w-100 rounded">Dates</h4>
        <p>{{question.created_at|date:"y-m-d H:m"}} <i class="fa fa-star-of-life"></i> {% trans "Ticket opening" %}</p>
        <p>{{question.viwed_at|date:"y-m-d H:m"}} <i class="fa fa-star-of-life"></i> {% trans "Taking into account" %}</p>
        {% for reponce in question.reponces.all reversed  %}
        <p>{{reponce.created_at|date:"y-m-d H:m"}} <span class="fa {{reponce.status}}"></span>{% trans "Action by" %} {{reponce.user}}</p>
        {% endfor %}
        <p>{% now "y-m-d H:m"%} <span class="fa fa-caret-down"></span> {% trans "Now" %}</p>

        <h4 class="text-center bg-dark py-2 text-white w-100 rounded">{% trans "Times" %}</h4>
        <p>{% trans "Taking into account" %} {{question.get_time_to_view}}</p>
        <p>{% trans "Time to first react" %} {{question.get_time_to_react}}</p>
        <p>{% trans "Time to resolve" %} {{question.get_time_to_resolv}}</p>

      </div>
    </div>
</div>
    <script src='{% static "js/medium-editor.js" %}'></script>

    </script>
          <script>
            var editor = new MediumEditor('.editable', {
              buttonLabels: 'fontawesome',
                  toolbar: {
                      buttons: ['bold', 'italic',  'justifyCenter',
                          'anchor', 'underline',  'strikethrough',
                          'subscript', 'superscript', 'anchor',
                          'quote', 'orderedlist', 'unorderedlist',
                          'indent', 'outdent', 'justifyLeft', 'justifyCenter',
                          'justifyRight', 'justifyFull',
                          'h1', 'h2', 'h3',  'h4', 'h5', 'h6',
                      ]
                  }
              });
          </script>

{% endblock %}

solutions/templates/solutions/reponce_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body_block %}
<main role="main" class="container mb-3 body_main emp-profile">
    <h1>New Reponce</h1>
    <form method="POST" class="post-form">
    {% csrf_token %}
      <button type="submit" class="save btn btn-default">Reponder</button>
    {% bootstrap_form form layout='horizontal' size='small'%}

    </form>

    <script>var editor = new MediumEditor('.editable');</script>

</main>
{% endblock %}