accounts/urls.py
from django.urls import path,reverse_lazy
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(),name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path('ajax/load_notification/',views.get_new_notification, name='load_notification'),
    path('notifications/',views.NotificationView.as_view(), name='notifications'),
    path('notifications/<pk>',views.notifications_redirectView, name='notifications_redirect'),
    path('notifications/<pk>/remove/',views.notifications_remove, name='notifications_remove'),
    path('notifications/<pk>/mark_as_read',views.notifications_markread, name='notifications_markread'),

    path("profile/",
        views.myProfileView,
        name="myprofile"),
    path("change_password",
        views.UserPasswordChang.as_view(),
        name="changepassword"),
    path("profile/<username>/edit",
        views.ProfileUpdateView.as_view(),
        name="edit"),
    path("ajax/made_consultant/<username>", views.made_consultant, name="made-consultant"),

    path("", views.UserListView.as_view(), name="list"),

    path("profile/<username>",
        views.ProfileUpdateView.as_view(),
        name="profile"),


    path("password-reset/",
        auth_views.PasswordResetView.as_view(template_name='accounts/password_reset_form.html',
                                            email_template_name="accounts/password_reset_email.html",
                                            success_url= reverse_lazy("login")),
        name="password-reset"),
    path("reset/<uidb64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',

                                                    success_url= reverse_lazy("home")    ),
        name="password_reset_confirm"),
    path("new_user/", views.NewUser.as_view(), name="new"),


]

clients/urls.py
from django.urls import path
from . import views
from accounts.views import NewUser as new_user

app_name = 'clients'

urlpatterns = [
    path("", views.ClientsList.as_view(),name='list'),
    path("new/", views.ClientsCreate.as_view(), name="new"),
    path("new_user/", new_user.as_view(), name="new_user"),

    #path("new/", views.clientsCreate, name="new"),

    #path("<slug>/", views.ClientsDetail.as_view(), name="detail"),
    path("<slug>/", views.ClientsUpdate.as_view(), name="detail"),

    path("<slug>/delete", views.ClientsDelete.as_view(), name="delete"),
    path("<slug>/edit", views.ClientsUpdate.as_view(), name="edit"),




]

ntonSulotions/urls.py
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf.urls import handler400, handler403, handler404, handler500
from django.conf import settings
from django.contrib import admin
from . import views

# urlpatterns = [path('?admin/', admin.site.urls), ]
  #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

# urlpatterns = i18n_patterns(
#     path("csv", views.csv_view, name="csv"),
#     path('i18n/', include('django.conf.urls.i18n')),
#     path('', views.HomePage.as_view(), name="home"),
#     path("admin/", admin.site.urls),
#     path("accounts/", include("accounts.urls", namespace="accounts")),
#     path("accounts/", include("django.contrib.auth.urls")),
#     path("ticket/", include("solutions.urls", namespace="solutions")),
#     path('client/', include('clients.urls',namespace='clients')),
#     path('set_language/<user_language>', views.set_language_from_url, name="set_language_from_url")
# )
urlpatterns = (
    path("csv", views.csv_view, name="csv"),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', views.HomePage.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("ticket/", include("solutions.urls", namespace="solutions")),
    path('client/', include('clients.urls',namespace='clients')),
    path('set_language/<user_language>', views.set_language_from_url, name="set_language_from_url")
)

handler400 = 'ntonSulotions.views.handler400'
handler403 = 'ntonSulotions.views.handler403'
handler404 = 'ntonSulotions.views.handler404'
handler500 = 'ntonSulotions.views.handler500'

solutions/urls.py
from django.urls import path, include, re_path
from . import views

app_name='solutions'


urlpatterns = [


    path('<int:pk>/', views.QuestionSingle.as_view(), name='questiondetail'),
    path('<int:pk>/edit',views.QuestionEdit.as_view(),name='questionedit'),
    path('nouvou/',views.QuestionCreate.as_view(),name='questioncreate'),
    path('<int:pk>/addanswere/',views.add_reponce_to_question,name='questionereponder'),
    path('<int:pk>/resolved/',views.questioneResolved,name='questioneResolved'),
    path('<int:pk>/charged/',views.questioneCharged,name='questioneCharged'),

    #path('page/<int:page>/',views.QuestionList.as_view(),name='questionlistpages'),
    path('',views.QuestionList.as_view(),name='questionlist'),
    path('ajax/load-categories/', views.load_categories, name='ajax_load_categorie'),
    path('ajax/load-chart/', views.load_chart, name='ajax_load_chart'),






]

accounts/models.py
from django.urls import  reverse_lazy
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import AbstractUser, UserManager as AbstractUserManager
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone

from clients import models as client
from solutions.models import Question

class UserManager(AbstractUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

class User(AbstractBaseUser , PermissionsMixin):
    username = models.CharField(_('Username'),unique=True, max_length=100)
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    tel = models.CharField(blank=True, max_length=40,verbose_name=_('Telephone'))
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
    is_active = models.BooleanField(_('active'), default=True)
    is_staff = models.BooleanField(_('Consultant'), default=False)
    supervisor = models.ForeignKey('self', unique=False, null=True, blank=True, related_name="consultants",on_delete=models.SET_NULL)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
    client = models.ForeignKey(client.Client, null=True, blank=True, related_name="users",on_delete=models.SET_NULL)
    lang = models.CharField(max_length=5, blank=True, default='fr')
    notify_by_email = models.BooleanField(default=True)
    notify_in_app = models.BooleanField(default=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
    def save(self, *args,**kwargs):
        self.validate_unique()
        super(User,self).save(*args, **kwargs)


    def get_full_name(self):
        '''
        Returns the first_name plus the last_name, with a space in between.
        '''
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        '''
        Returns the short name for the user.
        '''
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        '''
        Sends an email to this User.
        '''
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def __str__(self):
        return "{}".format(self.username)

    def get_absolute_url(self):
        return reverse_lazy("accounts:edit", kwargs={"username": self.username})

    def get_consultant(self):
        return User.objects.filter(is_staff = True)

    def add_notification(self, description_en, description_fr, url):
        notification = Notification.objects.create(user=self,description_en = description_en, description_fr =description_fr, url=url)
        notification.save

    def get_notification(self):
        querySet = Notification.objects.filter(user=self).update(new=False, seen= timezone.now())
        querySet = Notification.objects.filter(user=self)
        return querySet
    def get_last_10_notification(self):
        querySet = Notification.objects.filter(user=self).update(new=False)
        querySet = Notification.objects.filter(user=self)[:10]
        return querySet

    def get_new_notification(self):
        return Notification.objects.filter(user=self, new=True )

    def get_notification_count(self):
        return Notification.objects.filter(user=self, seen__isnull=True).count()
    def get_opened_ticket(self):
        return Question.objects.filter(user__client__charged_by__username = self.username, status='OV')


class Notification(models.Model):
    user = models.ForeignKey(User, related_name='notifications', on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now=True)
    description = models.TextField()
    url = models.CharField(max_length = 55)
    new = models.BooleanField(default=True)
    seen = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.description

    def viewed(self):
        self.seen = timezone.now()
        return self.save()

    def displayed(self):
        self.new = False

    class Meta:
        ordering = ["-date"]
        verbose_name = _('Notification')
        verbose_name_plural = _('Notifications')

solutions/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _

from django.db.models import Max
import os
import datetime
import uuid

from django.conf import settings
User = settings.AUTH_USER_MODEL



# Create your models here.
class Categorie(models.Model):
    """Django data model Categorie"""
    name = models.CharField(blank=True, max_length=100)
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categorys'
    def __str__(self):
        return str(self.name)

class SousCategorie(models.Model):
    """Django data model SousCategorie"""
    name = models.CharField(blank=True, max_length=100)
    categorie = models.ForeignKey('Categorie', on_delete=models.CASCADE, related_name='SousCategories',)
    class Meta:
        verbose_name = 'Sub-category'
        verbose_name_plural = 'Sub-categorys'
    def __str__(self):
        return str(self.categorie.name + '/'+self.name)

class Question(models.Model):

###           Priorite           ###
    Priorite=(
        ('F', _('Low')),
        ('M', _('Medium')),
        ('H', _('Height')),
        ('U', _('Urgent')),
        ('B',_('Blocking'))
        )
###           Status             ###
    Status= (
        ('EA', _('Waiting')),
        ('RS', _('Resolved')),
        ('OV', _('Open')),
        ('FR', _('Closed')),
        ('RF', _('Refused')),
        ('AN', _('Canceled')),
        ('DS', _('Deactiveted')),
        )

    def content_file_name(instance, filename):
        filename = "%s__%s" % (uuid.uuid4().hex[:6].upper(),filename)
        return os.path.join('images', str(instance.user.id), filename)
    def ref():
        this_year = datetime.date.today().year
        no = Question.objects.filter(created_at__year=this_year).aggregate(Max('ref')).get('ref__max')
        if no == None:
            return 1
        else:
            return  no + 1
    user = models.ForeignKey(User,null=True, related_name="tickets",on_delete=models.SET_NULL)
    ref = models.PositiveIntegerField(default=ref, verbose_name='Reference')
    # ref = models.CharField(default=ref, unique=True, editable=False,  max_length=100)
    created_at = models.DateTimeField(auto_now_add=True,editable=False)
    objet = models.CharField(max_length=200)
    image = models.ImageField(blank=True,null=True, upload_to=content_file_name)
    priorite=models.CharField(max_length=1,choices=Priorite,default='F',)
    status = models.CharField(max_length=2,choices=Status,default='OV',)
    priorite_intern = models.CharField(max_length=2, verbose_name=_('Internal priority'), choices=Priorite,default='F',blank=True,null=True)

    categorie = models.ForeignKey(Categorie,verbose_name=_('Category'), on_delete=models.CASCADE, related_name='quesions',)
    souscategorie = models.ForeignKey(SousCategorie, verbose_name=_('Sub-category'), on_delete=models.CASCADE, related_name='quesions',)

    description = models.TextField(blank=True,verbose_name=_('comment'))
    viwed_at = models.DateTimeField(blank=True,null=True)
    time_to_view = models.DurationField(blank=True,null=True,verbose_name=_('time to view'))
    charged_by = models.ForeignKey(User,null=True, related_name="charged_tickets",on_delete=models.SET_NULL)

    first_react_at = models.DateTimeField(blank=True,null=True)
    time_to_react = models.DurationField(blank=True,null=True,verbose_name=_('time to react'))
    resolved_at = models.DateTimeField(blank=True,null=True)
    time_to_resolv = models.DurationField(blank=True,null=True,verbose_name=_('Time to resolve'))
    last_action = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):

        if self.status != 'RS':
            self.resolved_at = None
            self.time_to_resolv = datetime.timedelta(0)
        if self.viwed_at:
            self.time_to_view = self.viwed_at - self.created_at
        if self.first_react_at:
            self.time_to_react = self.first_react_at - self.created_at
        if self.resolved_at  != None:
            self.time_to_resolv = self.resolved_at - self.created_at




        super().save(*args, **kwargs)

    def get_ref(self):
        return '{}-{}'.format(self.created_at.year,self.ref)
    def date_to_string(self,date, string, *args):
        if date:
            days = date.days
            sec = date.seconds
            if days == 1:
                return '%02d %s %02d H %02d M' % (days, _('Day'),int((sec/3600)%3600), int((sec/60)%60))
            if days > 1:
                return '%02d %s %02d H %02d M' % (days, _('Days'),int((sec/3600)%3600), int((sec/60)%60))
            return '%02d H %02d M' % (int((sec/3600)%3600), int((sec/60)%60))
        return string
    def get_time_to_resolv(self):
        string = _("Not resolved yet")
        return self.date_to_string(self.time_to_resolv, string)
    def get_time_to_view(self):
        string = _("Not viewed yet")
        return self.date_to_string(self.time_to_view, string)
    def get_time_to_react(self):
        string = _("Not reacted yet")
        return self.date_to_string(self.time_to_react, string)
    def get_resolved_at(self):
        if self.resolved_at: return self.resolved_at.strftime('%m/%d/%Y %H:%m')
        else : return  _("Not resolved yet")

    Color = {}
    Color['F'] = 'secondary'
    Color['M'] = 'primary'
    Color['H'] = 'success'
    Color['U'] = 'danger'

    def get_color(self):
        return self.Color.get(self.priorite)

    def get_categorie(self):
        return self.categorie.name + '/' + self.souscategorie.name

    def get_absolute_url(self):
            return reverse_lazy("solutions:questiondetail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.objet

    class Meta:
        ordering = ["-created_at"]
        verbose_name = _('Ticket')
        verbose_name_plural = _('Tickets')

class Reponce(models.Model):
    Status= (
        ('EA', _('Waiting')),
        ('RS', _('Resolved')),
        ('FR', _('Closed')),
        ('RF', _('Refused')),
        )
    user = models.ForeignKey(User,null=True, related_name="reponces",on_delete=models.SET_NULL)
    created_at = models.DateTimeField(auto_now_add=True,editable=False,)
    description = models.TextField(null=True, blank=True,)
    question = models.ForeignKey(Question,null=True, related_name="reponces",on_delete=models.SET_NULL)
    status = models.CharField(max_length=2,choices=Status,default='EA',)
    send_mail = models.BooleanField(default=False)
    def __str__(self):
        return self.description
    class Meta:
        ordering = ["-created_at"]

accounts/templates/accounts/notification_list.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap4 %}
{% block body_block %}


<div class=" fresh-table toolbar-color-green">
  <table id="fresh-table" class="table">
    <thead>
        <th data-field="username" data-sortable="true">{% trans "Date" %}</th>
        <th data-field="email" data-sortable="true">{% trans "Description" %}</th>
        <th data-field="actions" >Actions</th>
    </thead>
    <tbody>
  {% for notification in notification_list %}


      <tr id="n{{notification.pk}}"{% if not notification.seen %}class="bg-light"{% endif %}>
        <td>{{ notification.date}}</td>
        <td><a <a class="text-dark" href="{% url 'accounts:notifications_redirect' pk=notification.pk %}">{{ notification.description }}</a></td>
        <td>
          <a id="{{notification.pk}}remove"  rel="tooltip" title="Remove" class="table-action remove" href="javascript:void(0)" title="{% trans "Remove" %}">
           <i class="fa fa-remove"></i>
          </a>
        </td>
      </tr>
      <script type="text/javascript">

      $("#{{notification.pk}}remove").click(function () {
          $.ajax({url: "{% url 'accounts:notifications_remove' pk=notification.pk %}",
           success: function (data) {
                $("#n{{notification.pk}}").hide();
                $("#notification_count").html(data.notifications_count);

          }});
      });




      </script>
    {% endfor %}
    </tbody>
  </table>

</div>

















{% endblock %}

accounts/templates/accounts/password_change_form.html
{% extends "password_base.html" %}
{% load bootstrap4 %}


{% block body_block %}



      <form method="POST">
          {% csrf_token %}
          {% bootstrap_form form layout='horizontal' size='small'%}
          <input type="submit" value="Enregistre" class="btn btn-nton">

      </form>

  </div>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "password_base.html" %}
{% load bootstrap4 %}
{% load i18n %}

{% block body_block %}


    {% if form %}
    <div class="px-5">
      <form method="POST" class="p-2 px-5">
          {% csrf_token %}
          {% bootstrap_form form layout='horizontal' size='small'%}
          <input type="submit" value="Enregistre" class="btn btn-nton">

      </form>
    </div>

    {% else %}
    <div class="text-center py-5">
      <h1>Ooops</h1>
      <p class="text-center">{% trans "Warning, Something went wrong, please try again" %}</p>

    </div>

    {% endif %}


  </div>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
Someone asked for password reset for email {{email}}. Follow the link below:
{{protocol}}://{{domain}}{% url 'accounts:password_reset_confirm' uidb64=uid token=token%}

accounts/templates/accounts/password_reset_form.html
{% extends "password_base.html" %}
{% load bootstrap4 %}
{% load i18n %}



{% block body_block %}

    <h1 class="display-8">{% trans "Password reset" %}</h1>
    <p>{% trans "Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one." %}</p>

      <form method="POST">
          {% csrf_token %}
          {% bootstrap_form form layout='horizontal' size='small'%}
          <input type="submit" value="{% trans 'Reset password' %}" class="btn btn-nton">

      </form>

  </div>
{% endblock %}

accounts/templates/accounts/password_set_form.html
{% comment %} {% extends "base.html" %}
{% load bootstrap4 %}
{% load i18n %}

{% block body_block %}
<main role="main" class="container mb-3 body_main emp-profile">

  <form action="{% url 'accounts' %}" method="post">

    {% bootstrap_form form %}
    <button type="submit" name="button">{% trans "Set password" %}</button>
</main>
{% endblock %} {% endcomment %}

accounts/templates/accounts/user_form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}
{% load i18n %}


{% block body_block %}


  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-8">
          <div class="card">
            <div class="card-header card-header-success">
              <h4 class="card-title">{% trans "Edit Profile" %}</h4>
              <p class="card-category">{% trans "Complete your profile" %}</p>
            </div>
            <div class="card-body">
              <form action="{% url 'accounts:edit' username=user.username %}" method="post">
                {% csrf_token %}
                <div class="row">
                  <div class="col-md-6 form-group">
                    <div class="input-group bmd-form-group is-filled">
                      <div class="input-group-prepend">
                        <span class="input-group-text fa fa-user"></span>
                      </div>
                      <label for="id_username" class="bmd-label-static">{% trans "Display name" %}</label>
                      <input type="text" name="username" value="{{form.instance.username}}"
                      maxlength="100" class="tobeedited form-control-plaintext " title="" required="" id="id_username" readonly>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group" >
                      <div class="input-group bmd-form-group is-filled">
                        <label for="id_email" class="bmd-label-static">{% trans "Email address" %}</label>
                        <div class="input-group-prepend">
                          <span class="input-group-text fa fa-at"></span>
                        </div>
                        <input type="email" name="email" value="{{form.instance.email}}"
                        maxlength="254" class="tobeedited form-control-plaintext " title="" required="" id="id_email" readonly>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group disable" >
                      <div class="input-group bmd-form-group is-filled">
                        <!-- <div class="input-group-prepend">
                          <span class="input-group-text fa fa-user"></span>
                        </div> -->
                        <label for="id_first_name" class="bmd-label-static">{% trans "First name" %}</label>
                        <input type="text" name="first_name" value="{{form.instance.first_name}}"
                        maxlength="30" class="tobeedited form-control-plaintext" title="" id="id_first_name" readonly>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group " >
                      <div class="input-group bmd-form-group is-filled">
                        <!-- <div class="input-group-prepend">
                          <span class="input-group-text fa fa-user"></span>
                        </div> -->
                        <label for="id_last_name" class="bmd-label-static">{% trans "Last name" %}</label>
                        <input type="text" name="last_name" value="{{form.instance.last_name}}"
                        maxlength="30" class="tobeedited form-control-plaintext" title="" id="id_last_name" readonly>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row">

                  <div class="col-md-6">
                    <div class="form-group">
                      <div class="input-group bmd-form-group is-filled">
                        <div class="input-group-prepend">
                          <span class="input-group-text fa fa-phone"></span>
                        </div>
                        <label for="id_tel" class="bmd-label-static">{% trans "Telephone" %}</label>
                        <input type="text" name="tel" value="{{form.instance.tel}}"
                        maxlength="40" class="tobeedited form-control-plaintext" title="" id="id_tel" readonly></div>
                    </div>
                  </div>
                  {% if not user == request.user %}
                  <div class="col-md-4">
                    <div class="form-group" style="">
                      <div id="is_staff" class="is_staff form-check  collapse hide">
                        <label class="form-check-label">
                            <input type="checkbox" name="is_staff" disable=""
                            class="form-check-input" checked  id="id_is_staff" readonly>
                            Consultant
                            <span class="form-check-sign">
                                <span class="check"></span>
                            </span>
                        </label>
                      </div>
                    </div>
                  </div>

                  <div class="col-md-6">
                        {% bootstrap_field form.client %}
                  </div>
                  <div class="is_staff col-md-6 collapse hide">
                    {% bootstrap_field form.supervisor %}
                  </div>
                  {% endif %}
                </div>
                <button id="stertedit" type="button" class="btn btn-nton pull-left collapse show">{% trans "Edit" %}</button>
                <button id="send" type="submit" class="btn btn-nton pull-right collapse hide">{% trans "Update Profile" %}</button>
                <div class="clearfix"></div>
              </form>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card card-profile">
            <div class="card-avatar">
              <a href="javascript:;">
                <img class="img-fluid" src='{% if user.avatar %}{{user.avatar.url}}{% else %}{% static "img/avatar.png" %}{% endif %}' />
              </a>
            </div>
            <div class="card-body">
              {% if user == request.user %}
              <a class="profile-edit-btn btn btn-nton w-100 py-1 my-1"href="{% url 'accounts:changepassword'  %}">{% trans "Change password"  %}</a>
              {% endif %}
              {% if request.user.is_staff %}
              <form class="form-inline" action="{% url 'accounts:made-consultant' username=user.username %}" method="post">
                {% csrf_token %}
                {% if user.is_staff %}
                <button class="profile-edit-btn  btn btn-danger w-100 py-1 my-1" id="tagle-consultant" type="submit" name="button">{% trans "Remove from consultant list"  %}</button>
                {% else %}
                <button class="profile-edit-btn btn btn-warning w-100 py-1 my-1" id="tagle-consultant" type="submit" name="button">{% trans "Add to consultant list"  %}</button>
                {% endif %}
              </form>
              {% endif %}
            </div>
          </div>
        </div>
        <!-- <div class="row">
          <div class="col-12">
            <form>
              <div class="row">
                <div class="col">
                  <input type="text" name="start_date" class="form-control dateField" value='{{request.GET.start_date}}' placeholder='{% trans "Start date" %}'>
                </div>
                <div class="col">
                  <input type="text" name="end_date" class="form-control dateField" value='{{request.GET.end_date}}' placeholder='{% trans "End date" %}'>
                </div>
                <div class="col">
                  <button type="submit" class="btn btn-nton">{% trans "Filter" %}</button>
                </div>
              </div>
            </form>
          </div>
          <!-- <div class="col-md-5">
            <div class="card card-chart">
              <div class="card-header card-header-success">
                <div id="container" class="ct-chart" data-url="{% url 'solutions:ajax_load_chart' %}?type=pie&user={{user.username}}"></div>

              </div>
              <div class="card-body">
                <h4 class="card-title">{% trans "Tickets Status" %}</h4>
              </div>
            </div>
          </div>
          <div class="col-md-7">
            <div class="card card-chart">
              <div class="card-header card-header-warning">
                <div id="container2" class="ct-chart" data-url="{% url 'solutions:ajax_load_chart' %}?type=line&user={{user.username}}"></div>
              </div>
              <div class="card-body">
                <h4 class="card-title">{% if user.is_staff %}{% trans "Tickets take into account per day" %} {% else %}{% trans "Tickets opned per day" %}{% endif %}</h4>
              </div>
            </div>
          </div>
        </div> -->
      </div>
    </div>
  </div>
  <!-- <script src="https://code.highcharts.com/highcharts.src.js"></script> -->
  <script>
    // $.ajax({
    //   url: $("#container").attr("data-url"),
    //   dataType: 'json',
    //   success: function (data) {
    //     Highcharts.chart("container", data);
    //   }
    // });
    // $.ajax({
    //   url: $("#container2").attr("data-url"),
    //   dataType: 'json',
    //   success: function (data) {
    //     Highcharts.chart("container2", data);
    //   }
    // });
    </script>
  <script>
  function show_consutat() {
    var clientId = $("#id_client").children("option:selected").text();
    if (clientId == 'ntonadvisory') {
          $(".is_staff").collapse('show');
    }
    else {
      $(".is_staff").collapse('hide');
    }
  }

  $("#id_client").change(function () {
      show_consutat();
    });


    $("#stertedit").click(function () {
        $(".tobeedited").removeClass('form-control-plaintext');
        $(".tobeedited").addClass('form-control');
        $('.tobeedited').prop('readonly', false);
        $("#stertedit").collapse('hide');
        $("#send").collapse('show');


      });

  $(document).ready(function(){
      show_consutat();
    });
  </script>
{% endblock %}