clients/urls.py
from django.urls import path
from . import views
from accounts.views import NewUser as new_user

app_name = 'clients'

urlpatterns = [
    path("", views.ClientsList.as_view(),name='list'),
    path("new/", views.ClientsCreate.as_view(), name="new"),
    path("new_user/", new_user.as_view(), name="new_user"),

    #path("new/", views.clientsCreate, name="new"),

    #path("<slug>/", views.ClientsDetail.as_view(), name="detail"),
    path("<slug>/", views.ClientsUpdate.as_view(), name="detail"),

    path("<slug>/delete", views.ClientsDelete.as_view(), name="delete"),
    path("<slug>/edit", views.ClientsUpdate.as_view(), name="edit"),




]

ntonSulotions/urls.py
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf.urls import handler400, handler403, handler404, handler500
from django.conf import settings
from django.contrib import admin
from . import views

# urlpatterns = [path('?admin/', admin.site.urls), ]
  #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

# urlpatterns = i18n_patterns(
#     path("csv", views.csv_view, name="csv"),
#     path('i18n/', include('django.conf.urls.i18n')),
#     path('', views.HomePage.as_view(), name="home"),
#     path("admin/", admin.site.urls),
#     path("accounts/", include("accounts.urls", namespace="accounts")),
#     path("accounts/", include("django.contrib.auth.urls")),
#     path("ticket/", include("solutions.urls", namespace="solutions")),
#     path('client/', include('clients.urls',namespace='clients')),
#     path('set_language/<user_language>', views.set_language_from_url, name="set_language_from_url")
# )
urlpatterns = (
    path("csv", views.csv_view, name="csv"),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', views.HomePage.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("ticket/", include("solutions.urls", namespace="solutions")),
    path('client/', include('clients.urls',namespace='clients')),
    path('set_language/<user_language>', views.set_language_from_url, name="set_language_from_url")
)

handler400 = 'ntonSulotions.views.handler400'
handler403 = 'ntonSulotions.views.handler403'
handler404 = 'ntonSulotions.views.handler404'
handler500 = 'ntonSulotions.views.handler500'

clients/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils.text import slugify
from django.urls import reverse_lazy
from django.conf import settings
from solutions.models import Question

User = settings.AUTH_USER_MODEL

# Create your models here.
class Client(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name=_('Name'))
    address = models.TextField(blank=True,verbose_name=_('Address'))
    tel = models.CharField(blank=True, max_length=40,verbose_name=_('Telephone'))
    url = models.URLField(blank=True, verbose_name=_('Web site'))
    email = models.EmailField(verbose_name=_('DSI Email'))
    contact = models.CharField(blank=True,max_length=100,verbose_name=_('Contact'))
    contact_tel = models.CharField(blank=True,max_length=100,verbose_name=_("Contact's tel"))
    contact_email = models.EmailField(blank=True,verbose_name=_('Contact Email'))
    charged_by = models.ForeignKey(User,null=True, related_name="charged_clients",verbose_name=_('Resposable'),on_delete=models.SET_NULL)
    slug = models.SlugField(allow_unicode=True, unique=True)


    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.validate_unique()
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse_lazy('clients:detail',  kwargs={"slug": self.slug})


    class Meta:
        ordering = ["name"]
    def tickets(self):
        return Question.objects.filter(user__client__slug = self.slug)
    def tickets_open(self):
        return Question.objects.filter(user__client__slug = self.slug, status='OV')
    def tickets_waiting(self):
        return Question.objects.filter(user__client__slug = self.slug, status='EA')
    def tickets_resolved(self):
        return Question.objects.filter(user__client__slug = self.slug, status='RS')
    def tickets_Closed(self):
        return Question.objects.filter(user__client__slug = self.slug, status='FR')
    def tickets_Refused(self):
        return Question.objects.filter(user__client__slug = self.slug, status='RF')

clients/forms.py
from django import forms
from .models import Client
from accounts.models import User


class ClientForm(forms.ModelForm):

    class Meta:
        model = Client
        fields=['name','email','tel','url','address','contact','contact_tel','contact_email','charged_by']
        # widgets = {
        #     'url': forms.TextInput(attrs={'placeholder': 'http://'})
        # }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['charged_by'].queryset = User.objects.filter(is_staff = True)

clients/views.py
from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy,reverse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import CreateView,ListView, DetailView, UpdateView, DeleteView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from .models import  Client
from .forms import ClientForm
from djqscsv import render_to_csv_response,  write_csv
from django.contrib.auth.mixins import UserPassesTestMixin


class IsStaffTestMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff

def csv_view(request):
  qs = Client.objects.all()
  with open('Client.csv', 'wb') as csv_file:
      write_csv(qs, csv_file)
  return render_to_csv_response(qs)

class ClientsCreate(LoginRequiredMixin, UserPassesTestMixin,CreateView):
    model = Client
    form_class = ClientForm
    def test_func(self):
        return self.request.user.is_staff
    def form_valid(self, form):
        try:
            self.object = form.save(commit=False)
            self.object.save()
        except IntegrityError:
            messages.warning(self.request,_("Warning, Something went wrong, please try again"))
        else:
            messages.success(self.request,_("Client has been saved."))
            #success_url=reverse_lazy('clients:detail', slug=self.object.slug)
        return super().form_valid(form)

class ClientsDetail(LoginRequiredMixin,UserPassesTestMixin,DetailView):
    model = Client
    form_class = ClientForm
    template_name = 'clients/client_detail.html'
    def test_func(self):
        return self.request.user.is_staff
    def form_valid(self, form):
        try:
            self.object = form.save(commit=False)
            self.object.save()
        except IntegrityError:
            messages.warning(self.request,_("Warning, Something went wrong, please try again"))
        else:
            messages.success(self.request,_("Client has been saved."))
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ClientsDetail, self).get_context_data(**kwargs)
        context['form'] = ClientForm
        page = int(self.request.GET.get('page', 1))
        context['pages'] = [val for val in range(page - 5 , page + 5) if val > 0]
        context['activePage']= 'clientActive'
        return context

class ClientsUpdate(LoginRequiredMixin, UserPassesTestMixin,UpdateView):
    model= Client
    form_class = ClientForm
    template_name = 'clients/client_detail.html'

    def test_func(self):
        return self.request.user.is_staff

    def form_valid(self, form):
        try:
            self.object = form.save(commit=False)
            self.object.save()
        except IntegrityError:
            messages.warning(self.request,_("Warning, Something went wrong, please try again"))
        else:
            messages.success(self.request,_("Client has been saved."))
            success_url = reverse_lazy('clients:detail', slug=self.object.slug)

        return super().form_valid(form)

class ClientsList(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Client

    def test_func(self):
        return self.request.user.is_staff

    def get_queryset(self):
        # self.paginate_by =  int(self.request.GET.get('paginate_by', 10))

        if self.request.user.is_staff:
            clientlist =  Client.objects.all()
        else:
            raise Http404

        return clientlist

    def get_context_data(self, **kwargs):
        context = super(ClientsList, self).get_context_data(**kwargs)
        context['form'] = ClientForm
        # page = int(self.request.GET.get('page', 1))
        # context['pages'] = [val for val in range(page - 5 , page + 5) if val > 0]
        return context

class ClientsDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model= Client
    success_url=reverse_lazy('clients:list')
    def test_func(self):
        return self.request.user.is_staff


@login_required
def add_user(request, slug):
    client = get_object_or_404(Client, slug=slug)
    user = get_object_or_404(User, username=username)
    if request.method == "POST":
        try:
            user.client = client
            user.save()
        except IntegrityError:
            messages.warning(request,_("Warning, Something went wrong, please try again"))
        else:
            messages.success(request,_("ticket has been resolved, thanks for using owr platform."))
        return redirect('clients:detail', slug=self.object.slug)

    else:
        return redirect('clients:detail', slug=self.object.slug)

clients/templates/clients/client_confirm_delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load i18n %}
{% block body_block %}
<main role="main" class="container mb-3 body_main emp-profile">
<div class="py-3">
    <h1>{% trans "Delete Client" %}</h1>

    <form method="POST" enctype="multipart/form-data" class="post-form">
    {% csrf_token %}
    <button type="submit" class="save btn btn-danger text_right">{% trans "Delete" %}</button>
    <a href="{% url 'clients:detail' slug=client.slug %}">{% trans "Cancel" %}</a>
    </form>
</div>
</main>
{% endblock %}

clients/templates/clients/client_form.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% load i18n %}


{% block body_block %}
<!-- <link rel="stylesheet" href="{%static 'css/client.nton.css'%}?v=0.0.2" -->

<div class="container emp-profile">
  <div class="" id="home" >
    <div class="row">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header card-header-success">
            <h4 class="card-title">{% if form.instance.pk%}{{client}}
              {% else %}{% trans "New Client" %}
              {% endif %}</h4>
              <p class="card-category">{% trans "Complete le profile" %}</p>
            </div>
            <div class="card-body">
              <form  method="post">
                {% csrf_token %}
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      {% bootstrap_field form.name addon_before='<span class="input-group-text fa fa-briefcase "></span>' placeholder='' %}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      {% bootstrap_field form.email addon_before='<span class="input-group-text fa fa-envelope "></span>'  placeholder='' %}
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      {% bootstrap_field form.tel  addon_before='<span class="input-group-text fa fa-phone"></span>' placeholder='' %}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <a href="{{ form.instance.url }}">{{ form.instance.url }}</a>
                    <div  id="clientURLInput" class="form-group">
                      <div class="form-group">
                        <div class="form-group bmd-form-group is-filled">
                          <label for="id_url" class="bmd-label-static">{% trans "Site Internet" %}</label>
                          <div class="input-group">
                            <div class="input-group-prepend">
                            <span class="input-group-text">
                              <i class="fa"><img height='16' src='{% static "img/net.svg" %}'  alt="..."></i>
                            </span>
                            </div>
                            <input type="text" name="url" placeholder="http://" maxlength="200" class="form-control" title="" id="id_url">
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-4">
                    <div class="form-group">
                      {% bootstrap_field form.contact addon_before='<span class="input-group-text fa fa-user"></span>' placeholder='' %}
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div class="form-group">
                      {% bootstrap_field form.contact_tel addon_before='<span class="input-group-text fa fa-mobile "></span>' placeholder=''  %}
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div class="form-group">
                      {% bootstrap_field form.contact_email addon_before='<span class="input-group-text fa fa-envelope-open-text"></span>' placeholder=''  %}
                    </div>
                  </div>

                </div>
                <div class="row">
                  <div class="col-md-12">
                    {% bootstrap_field form.charged_by placeholder=''  %}
                  </div>
                  <div class="col-md-12">
                    {% bootstrap_field form.address addon_before='<i class="fas fa-location-arrow"></i>' placeholder=''  %}

                  </div>
                </div>
                <button id="send" type="submit" class="btn btn-nton pull-right">{% trans "New Client" %}</button>

              </form>
            </div>
        </div>
      </div>
    </div>
  </div>






{% endblock %}

clients/templates/clients/client_list.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load bootstrap4 %}


{% block body_block %}
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">
      {% trans "Clients" %}</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">
      {% trans "New Client" %}</a>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  {% comment %} Client tab {% endcomment %}
  <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
    {%  if client_list%}

    <div class="wrapper">


        <div class="fresh-table toolbar-color-green">
        <!--
          Available colors for the full background: full-color-blue, full-color-azure, full-color-green, full-color-red, full-color-orange
          Available colors only for the toolbar: toolbar-color-blue, toolbar-color-azure, toolbar-color-green, toolbar-color-red, toolbar-color-orange
        -->
          <table id="fresh-table" class="table">
            <thead>
              <th data-field="name" data-sortable="true">{% trans "Name" %}</th>
              <th data-field="email" data-sortable="true">{% trans "DSI Email" %}</th>
              <th data-field="contact" data-sortable="true">{% trans "Contact" %}</th>
              <th data-field="users" data-sortable="true">{% trans "Users" %}</th>

              <th data-field="actions" >Actions</th>
            </thead>
            <tbody>
              {% for client in client_list %}
              <tr>
                <td><a class="text-dark" href="{% url 'clients:detail' slug=client.slug %}">{{client.name}}</a></td>
                <td>{{ client.email}}</td>
                <td>{{ client.contact}}</td>
                <td>{{client.users.all.count}}</td>
                <td>
                  <a rel="tooltip" title="Edit" class="table-action edit" href="{% url 'clients:detail' slug=client.slug %}" title="Edit">
                    <i class="fa fa-edit"></i>
                  </a>
                  <a rel="tooltip" title="Remove" class="table-action remove" href="{% url 'clients:delete' slug=client.slug %}" title="Remove">
                   <i class="fa fa-remove"></i>
                  </a>
                </td>
                </tr>
                {% endfor %}
            </tbody>
          </table>
        </div>
      </div>

      {% else %}<h2>Pas de Client pour le moment!</h2>
      {%endif%}
  </div>
  {% comment %}New Client tab {% endcomment %}
    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">

      <div class="card">
        <div class="card-header card-header-success">
          <h4 class="card-title">{% trans "New Client" %}</h4>
            <p class="card-category">{% trans "Complete le profile" %}</p>
          </div>
          <div class="card-body">
            <form method="POST" enctype="multipart/form-data" action="{% url 'clients:new' %}">
              {% csrf_token %}
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    {% bootstrap_field form.name  addon_before='<span class="input-group-text fa fa-briefcase "></span>' placeholder='' %}
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    {% bootstrap_field form.email addon_before='<span class="input-group-text fa fa-envelope "></span>' placeholder='' %}
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    {% bootstrap_field form.tel addon_before='<span class="input-group-text fa fa-phone"></span>' placeholder='' %}
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <div class="form-group">
                      <div class="form-group bmd-form-group is-filled">
                        <label for="id_url" class="bmd-label-static">{% trans "Site Internet" %}</label>
                        <div class="input-group">
                          <div class="input-group-prepend">
                          <span class="input-group-text">
                            <i class="fa"><img height='16' src='{% static "img/net.svg" %}'  alt="..."></i>
                          </span>
                          </div>
                          <input type="text" name="url" placeholder="http://" maxlength="200" class="form-control" title="" id="id_url">
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-4">
                  <div class="form-group">
                    {% bootstrap_field form.contact addon_before='<span class="input-group-text fa fa-user"></span>' placeholder='' %}
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    {% bootstrap_field form.contact_tel addon_before='<span class="input-group-text fa fa-mobile "></span>' placeholder=''  %}
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    {% bootstrap_field form.contact_email addon_before='<span class="input-group-text fa fa-envelope-open-text"></span>' placeholder=''  %}
                  </div>
                </div>

              </div>
              <div class="row">
                <div class="col-md-12">
                  {% bootstrap_field form.charged_by placeholder=''  %}
                </div>
                <div class="col-md-12">
                  {% bootstrap_field form.address addon_before='<i class="fas fa-location-arrow"></i>' placeholder=''  %}

                </div>
              </div>
              <button type="submit" class="btn btn-nton pull-right">{% trans "New Client" %}</button>
              </form>
              </div>

            </div>
      </div>
</div>


  <script>
    var $table = $('#fresh-table')

    $(function () {
      $table.bootstrapTable({
        classes: 'table table-hover table-striped',
        toolbar: '.toolbar',

        search: true,
        showRefresh: false,
        showToggle: true,
        showColumns: true,
        pagination: true,
        striped: true,
        sortable: true,
        height: $(window).height(),
        pageSize: 25,
        pageList: [25, 50, 100],

        formatShowingRows: function (pageFrom, pageTo, totalRows) {
          return ''
        },
        formatRecordsPerPage: function (pageNumber) {
          return pageNumber + ' rows visible'
        }
      })



      $(window).resize(function () {
        $table.bootstrapTable('resetView', {
          height: $(window).height()
        })
      })
    })

  </script>


{% endblock %}