accounts/urls.py
from django.urls import path,reverse_lazy
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(),name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path('ajax/load_notification/',views.get_new_notification, name='load_notification'),
    path('notifications/',views.NotificationView.as_view(), name='notifications'),
    path('notifications/<pk>',views.notifications_redirectView, name='notifications_redirect'),
    path('notifications/<pk>/remove/',views.notifications_remove, name='notifications_remove'),
    path('notifications/<pk>/mark_as_read',views.notifications_markread, name='notifications_markread'),

    path("profile/",
        views.myProfileView,
        name="myprofile"),
    path("change_password",
        views.UserPasswordChang.as_view(),
        name="changepassword"),
    path("profile/<username>/edit",
        views.ProfileUpdateView.as_view(),
        name="edit"),
    path("ajax/made_consultant/<username>", views.made_consultant, name="made-consultant"),

    path("", views.UserListView.as_view(), name="list"),

    path("profile/<username>",
        views.ProfileUpdateView.as_view(),
        name="profile"),


    path("password-reset/",
        auth_views.PasswordResetView.as_view(template_name='accounts/password_reset_form.html',
                                            email_template_name="accounts/password_reset_email.html",
                                            success_url= reverse_lazy("login")),
        name="password-reset"),
    path("reset/<uidb64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',

                                                    success_url= reverse_lazy("home")    ),
        name="password_reset_confirm"),
    path("new_user/", views.NewUser.as_view(), name="new"),


]

clients/urls.py
from django.urls import path
from . import views
from accounts.views import NewUser as new_user

app_name = 'clients'

urlpatterns = [
    path("", views.ClientsList.as_view(),name='list'),
    path("new/", views.ClientsCreate.as_view(), name="new"),
    path("new_user/", new_user.as_view(), name="new_user"),

    #path("new/", views.clientsCreate, name="new"),

    #path("<slug>/", views.ClientsDetail.as_view(), name="detail"),
    path("<slug>/", views.ClientsUpdate.as_view(), name="detail"),

    path("<slug>/delete", views.ClientsDelete.as_view(), name="delete"),
    path("<slug>/edit", views.ClientsUpdate.as_view(), name="edit"),




]

ntonSulotions/urls.py
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf.urls import handler400, handler403, handler404, handler500
from django.conf import settings
from django.contrib import admin
from . import views

# urlpatterns = [path('?admin/', admin.site.urls), ]
  #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

# urlpatterns = i18n_patterns(
#     path("csv", views.csv_view, name="csv"),
#     path('i18n/', include('django.conf.urls.i18n')),
#     path('', views.HomePage.as_view(), name="home"),
#     path("admin/", admin.site.urls),
#     path("accounts/", include("accounts.urls", namespace="accounts")),
#     path("accounts/", include("django.contrib.auth.urls")),
#     path("ticket/", include("solutions.urls", namespace="solutions")),
#     path('client/', include('clients.urls',namespace='clients')),
#     path('set_language/<user_language>', views.set_language_from_url, name="set_language_from_url")
# )
urlpatterns = (
    path("csv", views.csv_view, name="csv"),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', views.HomePage.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("ticket/", include("solutions.urls", namespace="solutions")),
    path('client/', include('clients.urls',namespace='clients')),
    path('set_language/<user_language>', views.set_language_from_url, name="set_language_from_url")
)

handler400 = 'ntonSulotions.views.handler400'
handler403 = 'ntonSulotions.views.handler403'
handler404 = 'ntonSulotions.views.handler404'
handler500 = 'ntonSulotions.views.handler500'

solutions/urls.py
from django.urls import path, include, re_path
from . import views

app_name='solutions'


urlpatterns = [


    path('<int:pk>/', views.QuestionSingle.as_view(), name='questiondetail'),
    path('<int:pk>/edit',views.QuestionEdit.as_view(),name='questionedit'),
    path('nouvou/',views.QuestionCreate.as_view(),name='questioncreate'),
    path('<int:pk>/addanswere/',views.add_reponce_to_question,name='questionereponder'),
    path('<int:pk>/resolved/',views.questioneResolved,name='questioneResolved'),
    path('<int:pk>/charged/',views.questioneCharged,name='questioneCharged'),

    #path('page/<int:page>/',views.QuestionList.as_view(),name='questionlistpages'),
    path('',views.QuestionList.as_view(),name='questionlist'),
    path('ajax/load-categories/', views.load_categories, name='ajax_load_categorie'),
    path('ajax/load-chart/', views.load_chart, name='ajax_load_chart'),






]

clients/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils.text import slugify
from django.urls import reverse_lazy
from django.conf import settings
from solutions.models import Question

User = settings.AUTH_USER_MODEL

# Create your models here.
class Client(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name=_('Name'))
    address = models.TextField(blank=True,verbose_name=_('Address'))
    tel = models.CharField(blank=True, max_length=40,verbose_name=_('Telephone'))
    url = models.URLField(blank=True, verbose_name=_('Web site'))
    email = models.EmailField(verbose_name=_('DSI Email'))
    contact = models.CharField(blank=True,max_length=100,verbose_name=_('Contact'))
    contact_tel = models.CharField(blank=True,max_length=100,verbose_name=_("Contact's tel"))
    contact_email = models.EmailField(blank=True,verbose_name=_('Contact Email'))
    charged_by = models.ForeignKey(User,null=True, related_name="charged_clients",verbose_name=_('Resposable'),on_delete=models.SET_NULL)
    slug = models.SlugField(allow_unicode=True, unique=True)


    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.validate_unique()
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse_lazy('clients:detail',  kwargs={"slug": self.slug})


    class Meta:
        ordering = ["name"]
    def tickets(self):
        return Question.objects.filter(user__client__slug = self.slug)
    def tickets_open(self):
        return Question.objects.filter(user__client__slug = self.slug, status='OV')
    def tickets_waiting(self):
        return Question.objects.filter(user__client__slug = self.slug, status='EA')
    def tickets_resolved(self):
        return Question.objects.filter(user__client__slug = self.slug, status='RS')
    def tickets_Closed(self):
        return Question.objects.filter(user__client__slug = self.slug, status='FR')
    def tickets_Refused(self):
        return Question.objects.filter(user__client__slug = self.slug, status='RF')

solutions/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _

from django.db.models import Max
import os
import datetime
import uuid

from django.conf import settings
User = settings.AUTH_USER_MODEL



# Create your models here.
class Categorie(models.Model):
    """Django data model Categorie"""
    name = models.CharField(blank=True, max_length=100)
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categorys'
    def __str__(self):
        return str(self.name)

class SousCategorie(models.Model):
    """Django data model SousCategorie"""
    name = models.CharField(blank=True, max_length=100)
    categorie = models.ForeignKey('Categorie', on_delete=models.CASCADE, related_name='SousCategories',)
    class Meta:
        verbose_name = 'Sub-category'
        verbose_name_plural = 'Sub-categorys'
    def __str__(self):
        return str(self.categorie.name + '/'+self.name)

class Question(models.Model):

###           Priorite           ###
    Priorite=(
        ('F', _('Low')),
        ('M', _('Medium')),
        ('H', _('Height')),
        ('U', _('Urgent')),
        ('B',_('Blocking'))
        )
###           Status             ###
    Status= (
        ('EA', _('Waiting')),
        ('RS', _('Resolved')),
        ('OV', _('Open')),
        ('FR', _('Closed')),
        ('RF', _('Refused')),
        ('AN', _('Canceled')),
        ('DS', _('Deactiveted')),
        )

    def content_file_name(instance, filename):
        filename = "%s__%s" % (uuid.uuid4().hex[:6].upper(),filename)
        return os.path.join('images', str(instance.user.id), filename)
    def ref():
        this_year = datetime.date.today().year
        no = Question.objects.filter(created_at__year=this_year).aggregate(Max('ref')).get('ref__max')
        if no == None:
            return 1
        else:
            return  no + 1
    user = models.ForeignKey(User,null=True, related_name="tickets",on_delete=models.SET_NULL)
    ref = models.PositiveIntegerField(default=ref, verbose_name='Reference')
    # ref = models.CharField(default=ref, unique=True, editable=False,  max_length=100)
    created_at = models.DateTimeField(auto_now_add=True,editable=False)
    objet = models.CharField(max_length=200)
    image = models.ImageField(blank=True,null=True, upload_to=content_file_name)
    priorite=models.CharField(max_length=1,choices=Priorite,default='F',)
    status = models.CharField(max_length=2,choices=Status,default='OV',)
    priorite_intern = models.CharField(max_length=2, verbose_name=_('Internal priority'), choices=Priorite,default='F',blank=True,null=True)

    categorie = models.ForeignKey(Categorie,verbose_name=_('Category'), on_delete=models.CASCADE, related_name='quesions',)
    souscategorie = models.ForeignKey(SousCategorie, verbose_name=_('Sub-category'), on_delete=models.CASCADE, related_name='quesions',)

    description = models.TextField(blank=True,verbose_name=_('comment'))
    viwed_at = models.DateTimeField(blank=True,null=True)
    time_to_view = models.DurationField(blank=True,null=True,verbose_name=_('time to view'))
    charged_by = models.ForeignKey(User,null=True, related_name="charged_tickets",on_delete=models.SET_NULL)

    first_react_at = models.DateTimeField(blank=True,null=True)
    time_to_react = models.DurationField(blank=True,null=True,verbose_name=_('time to react'))
    resolved_at = models.DateTimeField(blank=True,null=True)
    time_to_resolv = models.DurationField(blank=True,null=True,verbose_name=_('Time to resolve'))
    last_action = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):

        if self.status != 'RS':
            self.resolved_at = None
            self.time_to_resolv = datetime.timedelta(0)
        if self.viwed_at:
            self.time_to_view = self.viwed_at - self.created_at
        if self.first_react_at:
            self.time_to_react = self.first_react_at - self.created_at
        if self.resolved_at  != None:
            self.time_to_resolv = self.resolved_at - self.created_at




        super().save(*args, **kwargs)

    def get_ref(self):
        return '{}-{}'.format(self.created_at.year,self.ref)
    def date_to_string(self,date, string, *args):
        if date:
            days = date.days
            sec = date.seconds
            if days == 1:
                return '%02d %s %02d H %02d M' % (days, _('Day'),int((sec/3600)%3600), int((sec/60)%60))
            if days > 1:
                return '%02d %s %02d H %02d M' % (days, _('Days'),int((sec/3600)%3600), int((sec/60)%60))
            return '%02d H %02d M' % (int((sec/3600)%3600), int((sec/60)%60))
        return string
    def get_time_to_resolv(self):
        string = _("Not resolved yet")
        return self.date_to_string(self.time_to_resolv, string)
    def get_time_to_view(self):
        string = _("Not viewed yet")
        return self.date_to_string(self.time_to_view, string)
    def get_time_to_react(self):
        string = _("Not reacted yet")
        return self.date_to_string(self.time_to_react, string)
    def get_resolved_at(self):
        if self.resolved_at: return self.resolved_at.strftime('%m/%d/%Y %H:%m')
        else : return  _("Not resolved yet")

    Color = {}
    Color['F'] = 'secondary'
    Color['M'] = 'primary'
    Color['H'] = 'success'
    Color['U'] = 'danger'

    def get_color(self):
        return self.Color.get(self.priorite)

    def get_categorie(self):
        return self.categorie.name + '/' + self.souscategorie.name

    def get_absolute_url(self):
            return reverse_lazy("solutions:questiondetail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.objet

    class Meta:
        ordering = ["-created_at"]
        verbose_name = _('Ticket')
        verbose_name_plural = _('Tickets')

class Reponce(models.Model):
    Status= (
        ('EA', _('Waiting')),
        ('RS', _('Resolved')),
        ('FR', _('Closed')),
        ('RF', _('Refused')),
        )
    user = models.ForeignKey(User,null=True, related_name="reponces",on_delete=models.SET_NULL)
    created_at = models.DateTimeField(auto_now_add=True,editable=False,)
    description = models.TextField(null=True, blank=True,)
    question = models.ForeignKey(Question,null=True, related_name="reponces",on_delete=models.SET_NULL)
    status = models.CharField(max_length=2,choices=Status,default='EA',)
    send_mail = models.BooleanField(default=False)
    def __str__(self):
        return self.description
    class Meta:
        ordering = ["-created_at"]

templates/base.old.html
<!DOCTYPE html>
{% load static%}
{% load i18n %}
{% load bootstrap4 %}
<html lang="fr" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>NTON ADVISORY</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {# Load CSS and JavaScript #}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/all.css'%}">
    <link rel="icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/offcanvas.css'%}">
    <!-- <link href="{% static 'css/wmd.css'%}" rel="stylesheet" /> -->
    <link rel="stylesheet" href="{%static 'css/master.nton.css'%}?v=1.0.3">
    <!-- HTML5 Shiv and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="bg-light">

{% comment %} top nav {% endcomment %}
<nav class="navbar navbar-expand-md navbar-light  font-weight-bold ">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img class="img-fluid" src=" {% static "images/logo.png" %}" alt="">
      </a>
      <button class="navbar-toggler mt-1" type="button" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
      </button>
        {% if user.is_authenticated %}
        <div class="collapse navbar-collapse flex-column align-items-start ml-lg-2 ml-0 " id="navbarCollapse">
            <span class="navbar-text ml-auto py-0 px-lg-2">

              <div class="nav justify-content-end " id="">
                  <li class="nav-item">
                    <a class="nav-link" href={% url 'accounts:profile' username=request.user.username %}>{{request.user.username}}</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}" >{% trans "Log out" %}</a>
                  </li>
                  <li class="nav-item d-md-none">
                    {% comment %} <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsE" aria-controls="navbarsExample08" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button> {% endcomment %}
                  </li>
                  </div>
              {%endif%}
            </span>
            {% if user.is_authenticated %}
            <ul class=" align-self-center navbar-nav mb-auto mt-0">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">{% trans "Home" %} </a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'solutions:questionlist'%}">Tickets</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'solutions:questioncreate'  %}">{% trans "New ticket" %}</a>
              </li>
              {% if request.user.is_staff %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Administration
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="nav-link" href="{% url 'clients:list'  %}">{% trans "Clients" %}</a>
                  <a class="nav-link mx-1" href="{% url 'accounts:list' %}" class="btn btn-simple">{% trans "Users" %}</a>
                </div>
              </li>
              {% endif %}
            </ul>
            {%endif%}
        </div>
</nav>

<div class="container">
  {% bootstrap_messages %}
</div>

<main role="main" class="container mb-3 body_main emp-profile">
{% block body_block %}
{% endblock %}
</main>
<div class="">
  {% block static_content %}
  {% endblock %}

</div>

<footer class="footer mt-auto py-3 bg-dark text-white">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-10 text-center">
        <p>Copyright ©
          <script>document.write(new Date().getFullYear());</script> Tous droits réservés | Fabriqué par <a href="http://ntonadvisory.com/" target="_blank">NTON.COM ADVISORY</a></p>
        </div>
        <div class="col text-center">
          <form class="form-inline my-2 ml-1 my-lg-0" action="{% url 'set_language' %}" method="post">
            {% csrf_token %}
            <input class="form-control mr-sm-2"  name="next" type="hidden" value="{{ redirect_to }}">
            <select class="dropdown form-control form-control-sm" name="language" onchange="this.form.submit()"> {% get_current_language as LANGUAGE_CODE %} {% get_available_languages as LANGUAGES %} {% get_language_info_list for LANGUAGES as languages %}
            {% for language in languages %}
              <option class="dropdown-item" value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %}
              selected disabled{% endif %}> {{ language.name_local }} ({{ language.code }})
              </option>
            {% endfor %}
          </select>
        </form>
      </div>
    </div>
  </div>
</footer>



<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"  crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"  crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="{% static 'js/nton.master.js'%}?v=0.0.2" type="text/javascript"></script>



  </body>
</html>

templates/password_base.html
{% load bootstrap4 %}
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <title>NTON ADVISORY</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  {# Load CSS and JavaScript #}

  <link rel="icon" href="{% static 'favicon.ico' %}">
  <link rel="stylesheet" href="{% static 'css/offcanvas.css'%}">
  <!-- <link href="{% static 'css/wmd.css'%}" rel="stylesheet" /> -->
  <link rel="stylesheet" href="{%static 'css/nton.login.css'%}?v=1.0.3">
  <!-- HTML5 Shiv and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
</head>
  <body>
    <div class="container-fluid">
      <div class="row no-gutter">
        <div class="d-none d-md-flex col-md-4 col-lg-5 bg-image justify-content-center align-items-center">
          <a href="{% url 'home' %}"><img src='{% static "img/logo.png" %}' width="295" height="86"  alt="NTON ADVISORY"></a>
        </div>
        <div class="col-md-8 col-lg-7">
          <div class="login d-flex align-items-center py-5">
            <div class="container">
              <div class="row">
                <div class="col-md-9 col-lg-8 mx-auto">
                  {% block body_block %}
                  {% endblock %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </body>
</html>
<link rel="stylesheet" href="{% static 'css/nton.login.css' %}">

templates/thanks.html
{% extends "base.html" %}
{% block body_block %}
<main role="main" class="container mb-3 body_main emp-profile">
<h1>Thanks for visiting! Come back soon!</h1>

</main>
{% endblock %}